ARG NODE_VERSION=14
ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/${BALENA_ARCH}-debian-node:$NODE_VERSION
EXPOSE 1883
WORKDIR /usr/src/app

COPY start.sh ./
COPY server.js ./
COPY package.json ./
COPY package-lock.json ./

RUN npm ci


CMD ["npm", "start"]
