name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Node Version
        run: |
          node --version
          npm --version
          docker --version
          
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Push
        run: |
          # docker buildx build --help
          # sh ./build-images.sh
          docker buildx build . --pull --build-arg BALENA_ARCH=armv7hf --platform $PLATFORM linux/arm/v7 --file Dockerfile.template --tag mithundotdas/telegram-block:armv7hf --load

